"""Second

Revision ID: 17908299d276
Revises: 50515cc1c030
Create Date: 2022-12-25 18:33:42.408924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17908299d276'
down_revision = '50515cc1c030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.alter_column("students", "tg_id", existing_type=sa.Integer(), type_=sa.BigInteger())
    op.alter_column("Chats", "tg_id", existing_type=sa.Integer(), type_=sa.BigInteger())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.alter_column("students", "tg_id", existing_type=sa.BigInteger(), type_=sa.Integer())
    op.alter_column("Chats", "tg_id", existing_type=sa.BigInteger(), type_=sa.Integer())
    
