"""Inital

Revision ID: 50515cc1c030
Revises: 
Create Date: 2022-12-25 00:05:10.674970

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '50515cc1c030'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ban_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('classes', sa.Column('mailing_time', sa.Time(), server_default="17:0:0", nullable=True))
    op.add_column('classes', sa.Column('mailing_stopped', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('mailing_time', sa.Time(), server_default="17:0:0", nullable=True))
    op.add_column('students', sa.Column('mailing_stopped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'mailing_stopped')
    op.drop_column('students', 'mailing_time')
    op.drop_column('classes', 'mailing_stopped')
    op.drop_column('classes', 'mailing_time')
    op.drop_table('Ban_list')
    # ### end Alembic commands ###


# CHANGELOG:
# Новая таблица: Ban_list
# Chats: 
# my_class = orm.relationship("Class", back_populates="chats")
# Class:
# mailing_time
# mailing_stopped
# bans
# Students:
# mailing_time
# mailing_stopped